/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_ii_projcect_lab;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author adelali
 */
public class InsertFrame extends javax.swing.JFrame {

    Statement stmt;
    ResultSet rs;
    ArrayList<String> Cols = new ArrayList<String>();
    ArrayList<JTextField> Fields = new ArrayList<JTextField>();
    Connection con;
    String _DBName;
    String _SelectedTable;

    /**
     * Creates new form InsertFrame
     */
    public InsertFrame(String DBName, String SelectedTable) throws ClassNotFoundException, SQLException {
        initComponents();
        _DBName = DBName;
        _SelectedTable = SelectedTable;
        JPanel mainlayout = new JPanel();
        GridBagConstraints c = new GridBagConstraints();
        c.anchor = GridBagConstraints.NORTHWEST;
        c.fill = GridBagConstraints.BOTH;
        c.weightx = 1;
        c.weighty = 1;
        setLayout(new GridBagLayout());
        setPreferredSize(new Dimension(500, 500));
        add(mainlayout);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        Class.forName("com.mysql.jdbc.Driver");

        con = DriverManager.getConnection(
                "jdbc:mysql://localhost:8889/dbproject?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8", "root", "root");

        stmt = con.createStatement();

        rs = stmt.executeQuery("SHOW COLUMNS FROM " + DBName + "." + SelectedTable);

        while (rs.next()) {

            Cols.add(rs.getString(1));
            

            JPanel container = new JPanel();
            JLabel jl = new JLabel(rs.getString(1));

            JTextField jtf = new JTextField();

            // container.set
            jl.setPreferredSize(new Dimension(70, 20));
            jtf.setPreferredSize(new Dimension(100, 30));
            Fields.add(jtf);

            container.add(jl);
            container.add(jtf);
            mainlayout.add(container);

        }

        con.close();
        this.setLayout(new BorderLayout());
        this.add(mainlayout);
        this.pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 313, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //create sql for insert
        //INSERT INTO `EMPLOYEE` (`Fname`, `Minit`, `Lname`, `Ssn`, `Bdate`, `Address`, `Sex`, `Salary`, `Super_ssn`, `Dno`, `Email`) VALUES ('wad', 'm', 'm', 'm', '2018-12-04', 'awdawd', 'w', '321', '123123', '1', 'adel50ali50@gmail.com');
        String SQL = "INSERT INTO `" + _DBName + "`.`" + _SelectedTable + "` ";

        SQL = SQL + "(";
        for (int i = 0; i < Cols.size(); i++) {
            SQL = SQL + "`";
            SQL = SQL + Cols.get(i).toString();
            SQL = SQL + "`";

            if (i != Cols.size() - 1) {
                SQL = SQL + " , ";
            }
        }
        SQL = SQL + ")  VALUES (";
        for (int i = 0; i < Fields.size(); i++) {
             SQL = SQL + "'";
             SQL = SQL + Fields.get(i).getText().toString();
            SQL = SQL + "'";
             if (i != Cols.size() - 1) {
                SQL = SQL + " , ";
            }
        }
        SQL = SQL + ");";
        System.out.println(SQL);
         Connection conN;
        try {
            conN = DriverManager.getConnection(
                    "jdbc:mysql://localhost:8889/dbproject?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8", "root", "root");
                 stmt = conN.createStatement();
                       int UResult =(stmt.executeUpdate(SQL));
                         if (UResult==1){
                             
                             JOptionPane.showConfirmDialog(rootPane, " Success " +SQL);
                         }else{
                              JOptionPane.showConfirmDialog(rootPane, " Failed "+SQL);
                         }
                 conN.close();
        
        } catch (SQLException ex) {
             JOptionPane.showConfirmDialog(rootPane , ex.getSQLState()+" " +SQL);
            Logger.getLogger(InsertFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

                      
                       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InsertFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
